export default {
    SUCCESS_RESPONSE_STATE: '200',
    PARAM_ERROR_RESPONSE_STATE: '400',
    TOKEN_ERROR_RETURN_STATE: '401',

    TABLE_EXTRA_SMALL_WIDTH: 60,
    TABLE_SMALL_WIDTH: 120,
    TABLE_BASE_WIDTH: 180,
    TABLE_MEDIUM_WIDTH: 240,
    TABLE_LARGE_WIDTH: 300,
    TABLE_EXTRA_LARGE_WIDTH: 600,

    TABLE_DEFAULT_HEIGHT: 56 * 12 + 59,

    loginMsg: ''

}